// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: badges.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserBadge = `-- name: CreateUserBadge :one
INSERT INTO user_badges (user_id, badge_code)
VALUES ($1, $2)
ON CONFLICT (user_id, badge_code) DO NOTHING
RETURNING user_id
`

type CreateUserBadgeParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	BadgeCode string      `json:"badge_code"`
}

func (q *Queries) CreateUserBadge(ctx context.Context, arg CreateUserBadgeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUserBadge, arg.UserID, arg.BadgeCode)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
