// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Achievement struct {
	Code             string `json:"code"`
	Name             string `json:"name"`
	AchievementGroup string `json:"achievement_group"`
	Position         int32  `json:"position"`
}

type Badge struct {
	Code                 string `json:"code"`
	Name                 string `json:"name"`
	RequiredAchievements int32  `json:"required_achievements"`
}

type OutboxEvent struct {
	ID          pgtype.UUID        `json:"id"`
	EventType   string             `json:"event_type"`
	AggregateID pgtype.UUID        `json:"aggregate_id"`
	Payload     []byte             `json:"payload"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	BadgeCode         string             `json:"badge_code"`
	AmountKobo        int64              `json:"amount_kobo"`
	ProviderReference pgtype.Text        `json:"provider_reference"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Purchase struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	ExternalID string             `json:"external_id"`
	AmountKobo int64              `json:"amount_kobo"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	Phone          pgtype.Text        `json:"phone"`
	PaymentAccount pgtype.Text        `json:"payment_account"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type UserAchievement struct {
	UserID          pgtype.UUID        `json:"user_id"`
	AchievementCode string             `json:"achievement_code"`
	UnlockedAt      pgtype.Timestamptz `json:"unlocked_at"`
}

type UserBadge struct {
	UserID     pgtype.UUID        `json:"user_id"`
	BadgeCode  string             `json:"badge_code"`
	UnlockedAt pgtype.Timestamptz `json:"unlocked_at"`
}
