// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Achievement struct {
	Code             string `json:"code"`
	Name             string `json:"name"`
	AchievementGroup string `json:"achievement_group"`
	Position         int32  `json:"position"`
}

type Badge struct {
	Code                 string `json:"code"`
	Name                 string `json:"name"`
	RequiredAchievements int32  `json:"required_achievements"`
}

type OutboxEvent struct {
	ID          uuid.UUID       `json:"id"`
	EventType   string          `json:"event_type"`
	AggregateID uuid.UUID       `json:"aggregate_id"`
	Payload     json.RawMessage `json:"payload"`
	PublishedAt sql.NullTime    `json:"published_at"`
	CreatedAt   time.Time       `json:"created_at"`
}

type Payment struct {
	ID                uuid.UUID      `json:"id"`
	UserID            uuid.UUID      `json:"user_id"`
	BadgeCode         string         `json:"badge_code"`
	AmountKobo        int64          `json:"amount_kobo"`
	ProviderReference sql.NullString `json:"provider_reference"`
	Status            string         `json:"status"`
	CreatedAt         time.Time      `json:"created_at"`
}

type Purchase struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	ExternalID string    `json:"external_id"`
	AmountKobo int64     `json:"amount_kobo"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID             uuid.UUID      `json:"id"`
	Name           string         `json:"name"`
	Email          string         `json:"email"`
	Phone          sql.NullString `json:"phone"`
	PaymentAccount sql.NullString `json:"payment_account"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type UserAchievement struct {
	UserID          uuid.UUID `json:"user_id"`
	AchievementCode string    `json:"achievement_code"`
	UnlockedAt      time.Time `json:"unlocked_at"`
}

type UserBadge struct {
	UserID     uuid.UUID `json:"user_id"`
	BadgeCode  string    `json:"badge_code"`
	UnlockedAt time.Time `json:"unlocked_at"`
}
