// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBusEvent = `-- name: CreateBusEvent :one
INSERT INTO outbox_events (
  id,
  event_type,
  aggregate_id,
  payload,
  created_at
) VALUES (
  $1, $2, $3, $4, $5
)
ON CONFLICT DO NOTHING
RETURNING id, event_type, aggregate_id, payload, published_at, created_at
`

type CreateBusEventParams struct {
	ID          pgtype.UUID        `json:"id"`
	EventType   string             `json:"event_type"`
	AggregateID pgtype.UUID        `json:"aggregate_id"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateBusEvent(ctx context.Context, arg CreateBusEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createBusEvent,
		arg.ID,
		arg.EventType,
		arg.AggregateID,
		arg.Payload,
		arg.CreatedAt,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateID,
		&i.Payload,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingOutBusEvent = `-- name: GetPendingOutBusEvent :many
SELECT id, event_type, aggregate_id, payload, published_at, created_at
FROM outbox_events
WHERE published_at IS NULL
ORDER BY created_at
LIMIT $1
`

func (q *Queries) GetPendingOutBusEvent(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getPendingOutBusEvent, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateID,
			&i.Payload,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventProcessed = `-- name: MarkOutboxEventProcessed :exec
UPDATE outbox_events
SET published_at = NOW()
WHERE id = $1
  AND published_at IS NULL
`

func (q *Queries) MarkOutboxEventProcessed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventProcessed, id)
	return err
}
