// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
  id,
  user_id,
  badge_code,
  amount_kobo,
  status,
  created_at
) VALUES (
  $1, $2, $3, $4, $5, $6
)
ON CONFLICT (user_id, badge_code) DO NOTHING
RETURNING id
`

type CreatePaymentParams struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	BadgeCode  string             `json:"badge_code"`
	AmountKobo int64              `json:"amount_kobo"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.UserID,
		arg.BadgeCode,
		arg.AmountKobo,
		arg.Status,
		arg.CreatedAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const markPaymentFailed = `-- name: MarkPaymentFailed :exec
UPDATE payments
SET status = 'failed',
  provider_reference = $2
WHERE id = $1
`

type MarkPaymentFailedParams struct {
	ID                pgtype.UUID `json:"id"`
	ProviderReference pgtype.Text `json:"provider_reference"`
}

func (q *Queries) MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) error {
	_, err := q.db.Exec(ctx, markPaymentFailed, arg.ID, arg.ProviderReference)
	return err
}

const markPaymentSuccessful = `-- name: MarkPaymentSuccessful :exec
UPDATE payments
SET status = 'successful',
  provider_reference = $2
WHERE id = $1
`

type MarkPaymentSuccessfulParams struct {
	ID                pgtype.UUID `json:"id"`
	ProviderReference pgtype.Text `json:"provider_reference"`
}

func (q *Queries) MarkPaymentSuccessful(ctx context.Context, arg MarkPaymentSuccessfulParams) error {
	_, err := q.db.Exec(ctx, markPaymentSuccessful, arg.ID, arg.ProviderReference)
	return err
}
