// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: purchases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPurchasesByUser = `-- name: CountPurchasesByUser :one
SELECT COUNT(*)::int AS total_purchases
FROM purchases
WHERE user_id = $1
`

func (q *Queries) CountPurchasesByUser(ctx context.Context, userID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPurchasesByUser, userID)
	var total_purchases int32
	err := row.Scan(&total_purchases)
	return total_purchases, err
}

const createPurchase = `-- name: CreatePurchase :one
INSERT INTO purchases (
  id,
  user_id,
  external_id,
  amount_kobo
) VALUES (
  $1, $2, $3, $4
)
ON CONFLICT (id) DO NOTHING
RETURNING id, user_id, external_id, amount_kobo, created_at
`

type CreatePurchaseParams struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	ExternalID string      `json:"external_id"`
	AmountKobo int64       `json:"amount_kobo"`
}

func (q *Queries) CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error) {
	row := q.db.QueryRow(ctx, createPurchase,
		arg.ID,
		arg.UserID,
		arg.ExternalID,
		arg.AmountKobo,
	)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExternalID,
		&i.AmountKobo,
		&i.CreatedAt,
	)
	return i, err
}
