// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountPurchasesByUser(ctx context.Context, userID pgtype.UUID) (int32, error)
	CountUserAchievement(ctx context.Context, userID pgtype.UUID) (int64, error)
	CreateBusEvent(ctx context.Context, arg CreateBusEventParams) (OutboxEvent, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (pgtype.UUID, error)
	CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserBadge(ctx context.Context, arg CreateUserBadgeParams) (pgtype.UUID, error)
	GetUser(ctx context.Context, id pgtype.UUID) (GetUserRow, error)
	InsertUserAchievement(ctx context.Context, arg InsertUserAchievementParams) (pgtype.UUID, error)
	MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) error
	MarkPaymentSuccessful(ctx context.Context, arg MarkPaymentSuccessfulParams) error
	UpdateUserPaymentAccount(ctx context.Context, arg UpdateUserPaymentAccountParams) (UpdateUserPaymentAccountRow, error)
}

var _ Querier = (*Queries)(nil)
