// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_achievement.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserAchievement = `-- name: CountUserAchievement :one
SELECT COUNT(*)
FROM user_achievements
WHERE user_id = $1
`

func (q *Queries) CountUserAchievement(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserAchievement, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserAchievements = `-- name: GetUserAchievements :one
SELECT
    COALESCE(
        ARRAY_AGG(a.name ORDER BY a.achievement_group, a.position)
        FILTER (WHERE ua.user_id IS NOT NULL),
        '{}'
    ) AS unlocked_achievements,

    COALESCE(
        ARRAY_AGG(a.name ORDER BY a.achievement_group, a.position)
        FILTER (
            WHERE ua.user_id IS NULL
              AND NOT EXISTS (
                  SELECT 1
                  FROM achievements previous
                  WHERE previous.achievement_group = a.achievement_group
                    AND previous.position < a.position
                    AND NOT EXISTS (
                        SELECT 1
                        FROM user_achievements previous_ua
                        WHERE previous_ua.user_id = $1
                          AND previous_ua.achievement_code = previous.code
                    )
              )
        ),
        '{}'
    ) AS next_available_achievements

FROM achievements a
LEFT JOIN user_achievements ua
    ON ua.achievement_code = a.code
    AND ua.user_id = $1
`

type GetUserAchievementsRow struct {
	UnlockedAchievements      interface{} `json:"unlocked_achievements"`
	NextAvailableAchievements interface{} `json:"next_available_achievements"`
}

func (q *Queries) GetUserAchievements(ctx context.Context, userID pgtype.UUID) (GetUserAchievementsRow, error) {
	row := q.db.QueryRow(ctx, getUserAchievements, userID)
	var i GetUserAchievementsRow
	err := row.Scan(&i.UnlockedAchievements, &i.NextAvailableAchievements)
	return i, err
}

const insertUserAchievement = `-- name: InsertUserAchievement :one
INSERT INTO user_achievements (user_id, achievement_code)
VALUES ($1, $2)
ON CONFLICT (user_id, achievement_code) DO NOTHING
RETURNING user_id
`

type InsertUserAchievementParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	AchievementCode string      `json:"achievement_code"`
}

func (q *Queries) InsertUserAchievement(ctx context.Context, arg InsertUserAchievementParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertUserAchievement, arg.UserID, arg.AchievementCode)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
