// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_achievement.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserAchievement = `-- name: CountUserAchievement :one
SELECT COUNT(*)
FROM user_achievements
WHERE user_id = $1
`

func (q *Queries) CountUserAchievement(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserAchievement, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertUserAchievement = `-- name: InsertUserAchievement :one
INSERT INTO user_achievements (user_id, achievement_code)
VALUES ($1, $2)
ON CONFLICT (user_id, achievement_code) DO NOTHING
RETURNING user_id
`

type InsertUserAchievementParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	AchievementCode string      `json:"achievement_code"`
}

func (q *Queries) InsertUserAchievement(ctx context.Context, arg InsertUserAchievementParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertUserAchievement, arg.UserID, arg.AchievementCode)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
