// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name,
    email,
    phone,
    payment_account
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, name, email, phone, payment_account, created_at, updated_at
`

type CreateUserParams struct {
	Name           string      `json:"name"`
	Email          string      `json:"email"`
	Phone          pgtype.Text `json:"phone"`
	PaymentAccount pgtype.Text `json:"payment_account"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.PaymentAccount,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PaymentAccount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, phone, payment_account, created_at
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	Phone          pgtype.Text        `json:"phone"`
	PaymentAccount pgtype.Text        `json:"payment_account"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PaymentAccount,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPaymentAccount = `-- name: UpdateUserPaymentAccount :one
UPDATE users
SET payment_account = $2
WHERE id = $1
RETURNING id, name, email, phone, payment_account, created_at
`

type UpdateUserPaymentAccountParams struct {
	ID             pgtype.UUID `json:"id"`
	PaymentAccount pgtype.Text `json:"payment_account"`
}

type UpdateUserPaymentAccountRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	Phone          pgtype.Text        `json:"phone"`
	PaymentAccount pgtype.Text        `json:"payment_account"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateUserPaymentAccount(ctx context.Context, arg UpdateUserPaymentAccountParams) (UpdateUserPaymentAccountRow, error) {
	row := q.db.QueryRow(ctx, updateUserPaymentAccount, arg.ID, arg.PaymentAccount)
	var i UpdateUserPaymentAccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PaymentAccount,
		&i.CreatedAt,
	)
	return i, err
}
